### ISSUE TITLE
Speed up preparation of raster data

### ISSUE THREAD

**Issue by ymutua** [SFrav/Techfit#2]
I suspect `resample` is the one causing problems. Try using `gdalwarp` then set resolution and resampling via its -tr  and -r arguments respectively. Can I have a sample dataset to play around with?

**Comment by SFrav** [comment]
The main culprit is the `projectRaster` function. gdalwarp is much faster. Doing the resampling in one step will make it even quicker. 
This works without the target resolution flag:
`gdalwarp(srcfile = "MCD12Q2.A2015001.h20v09.006.2019046134140_greenup1.tif", dstfile ="greenup1_1.tif", s_srs = "+proj=sinu +lon_0=0 +x_0=0 +y_0=0 +a=6371007.181 +b=6371007.181 +units=m +no_defs", t_srs = "+proj=longlat +datum=WGS84 +no_defs", r = "bilinear")`

Adding `tr = c(300, 300)` gives an `exit status 1` error. 

Here's the call to gdal:
`'"C:\Program Files\QGIS 2.18\bin\gdalwarp.exe" -tr 300 300 -s_srs "+proj=sinu +lon_0=0 +x_0=0 +y_0=0 +a=6371007.181 +b=6371007.181 +units=m +no_defs" -t_srs "+proj=longlat +datum=WGS84 +no_defs" -r "bilinear" -of "GTiff" "MCD12Q2.A2015001.h20v09.006.2019046134140_greenup1.tif" "greenup1_1.tif"'`

**Comment by ymutua** [comment]
Did you find any solution for this?

**Comment by SFrav** [comment]
No solution yet. At the moment, I have left the resampling until later.

**Comment by ymutua** [comment]
Looks like you dealt with this

**Comment by SFrav** [comment]
In multiple steps, if I recall correctly. Much faster though.
